### ISSUE TITLE
Problem Translation

### ISSUE THREAD

**Issue by angelkurten** [StydeNet/html#11]
Bueno pues nada tengo el siguiente problema:
```html
<div class="form-group">
    <label  class="col-lg-2 col-sm-2 control-label">{{ trans('auth::ui.role.description') }}</label>
    <div class="col-lg-8">

        {!! Form::text('description', null, ['class' => 'form-control']) !!}

    </div>
</div>
```

Ahora como ves uso las traducciones para los label, y esto me genera un problema al trabajar con tu paquete, porque si coloco una traduccion esta no va a coincidir con el nombre del campo esperado

**Comment by sileence** [comment]
This package supports label translations out of the box, you don't need to edit the templates.

Por favor lee la sección "Labels" en la documentación de Field builder, aquí tienes el enlace en español:

https://github.com/StydeNet/html/blob/master/docs/es/field-builder.md
