### ISSUE TITLE
Alert session error

### ISSUE THREAD

**Issue by FlemingRMT** [StydeNet/html#12]
ErrorException in Container.php line 144:
array_merge(): Argument 1 is not an array

cloning html-integration-tests

and going to
html-integration-tests/public/alert/success url

$this->handler->getPreviousMessages() return "null" in Container.php

**Comment by sileence** [comment]
Thank you for reporting the bug, I'll take a look at it.

**Comment by sileence** [comment]
This should be fixed now, please update your local integration test repository, then execute composer update and try again. If the error persists feel free to open the issue again and notify me.
