### ISSUE TITLE
Error in persistence of alert messages in session for Laravel 5.8

### ISSUE THREAD

**Issue by nachofassini** [StydeNet/html#123]
Alerts are being lost among the requests.

Using middleware `\ Styde \ Html \ Alert \ Middleware :: class` it is not working.

I'm using `alert ('Hello')` and then `redirect () -> route ('index')`

Where in the view of the route `index` I have the `{!! Alert :: render () !!}`

It seems that someone already raised a pull request correcting this problem: https://github.com/StydeNet/html/pull/120

**Comment by sileence** [comment]
@nachofassini thanks for letting me know and sorry about the delay, I have merged the PR and tagged the version 1.7.1 of this component.
