### ISSUE TITLE
Undefined index: theme

### ISSUE THREAD

**Issue by InriOma** [StydeNet/html#129]
Instalé Styde/Html en mi laravel 6 y obtengo el siguiente error

Undefined index: theme

me marca la siguiente linea

$this->theme = new Theme($this->app['view'], $this->options['theme'], $this->options['custom']);

vendor\styde\html\src\HtmlServiceProvider.php:110

**Comment by sileence** [comment]
@InriOma disculpa por la demora, no he podido reproducir este problema. Prueba limpiando el caché de la configuración o por favor provee más información o sube un ejemplo para revisarlo. Muchos saludos.

**Comment by lsfiege** [comment]
Yo pude reproducir el issue @sileence , se produce al ejecutar `php artisan config:cache` teniendo una instalación fresca del componente en un proyecto con laravel 6 (sin publicar sus archivos de configuración)

**Comment by sileence** [comment]
Muchas gracias, @lsfiege.

Ya está solucionado en la versión 1.8.1.

cc @InriOma

**Comment by InriOma** [comment]
Muchas Gracias. Saludos.,

Thanks, regards

**Comment by jurekhernandez** [comment]
Buenas tardes, 
Como solucionaron este problema ???
agregue la versión   "styde/html": "^1.9"
y de igual forma me muestra el error,
hice el paso a paso 2 veces y no entiendo el error 
con y sin publicar la configuración  pero de igual forma no funciona


![image](https://user-images.githubusercontent.com/8306222/85209594-27143480-b307-11ea-9aa9-e76f7774f167.png)
