### ISSUE TITLE
There will be support for Laravel 7?

### ISSUE THREAD

**Issue by lsfiege** [StydeNet/html#131]
Hello, I was wondering about if this package will add support for Laravel 7 since [laravel collective has done it](https://github.com/LaravelCollective/html/commits/v6.1.0)

I have investigated if it's possible for me to do a PR, but the phpspec dependencies do not satisfy symfony 5 yet  :(

**Comment by sileence** [comment]
Ya está. Revisa la versión 1.9.0

También estoy trabajando en el desarrollo de una nueva versión para Laravel 7. El Progreso está documentado aquí: https://styde.net/creacion-de-componentes-para-laravel/

Muchos saludos.
