### ISSUE TITLE
Empty option in select

### ISSUE THREAD

**Issue by helmerdavila** [StydeNet/html#19]
When i tried to generate a select (multiselect), this create a empty option selectable. This happens in common select too.
This is my two suggestions.
1. No empty field when ['empty' => false]
2. Disabled option ['empty' => ['Select your option', disabled]].
Thank you.

**Comment by sileence** [comment]
Done, thank you for reporting the issue.

**Comment by nicolaeturcan** [comment]
Very useful, but unfortunately it was hard to find out. Thanks!
