### ISSUE TITLE
Send extra variable to template

### ISSUE THREAD

**Issue by leyvicaz** [StydeNet/html#21]
It would be nice to have a method to send variables external to the template. As "$label"

**Comment by sileence** [comment]
@leyvicaz I'm thinking about this, maybe passing an additional array?

`
{!! Field::text('name', 'Duilio', [], ['col' => '12']) !!}
`

Maybe too many arguments? Or:

`
{!! Field::text('name', 'Duilio', ['extra' => ['col' => '12']]) !!}
`

But I don't like the double array.

**Comment by sileence** [comment]
Done, yo can now pass it as an additional argument after the array of attributes, example:


`
{!! Field::text('name', 'Duilio', [], ['col' => '12']) !!}
`

Thank you for reporting the issue, let me know if you find another inconvenience.

Regards.
