### ISSUE TITLE
Add the reserved word return the input method on FieldBuilder.php

### ISSUE THREAD

**Issue by dctrndrk** [StydeNet/html#25]
/**
     * Create a form input field.
     *
     * @param string $type
     * @param string $name
     * @param string $value
     * @param array  $attributes
     *
     * @return string
     */
    public function input($type, $name, $value = null, $attributes = array())
    {
        return $this->build($type, $name, $value, $attributes);
    }

**Comment by sileence** [comment]
fixed, thank you
