### ISSUE TITLE
Checkboxes with only one item bug

### ISSUE THREAD

**Issue by vnponce** [StydeNet/html#29]
Get an wrong name when $options array is only one item. 

Code:
`{!! Form::checkboxes('remember', ['remember' => 'Recordar'], ['remember']) !!}`

Result an input name 'remember[]' : 
```
<div class="checkbox">
    <label>
        <input id="remember_remember" checked="checked" name="remember[]" type="checkbox" value="remember">
        Recordar
    </label>
</div>
```

**Comment by sileence** [comment]
This doesn't seem like an actual bug, if you want only one checkbox, then use the "checkbox" method instead of "checkboxes"

`{!! Form::checkbox('remember') !!}`

o

`{!! Field::checkbox('remember') !!}`
