### ISSUE TITLE
url undefined

### ISSUE THREAD

**Issue by ayalaarevalo** [StydeNet/html#3]
Estaba probando tu package, detecte que cuando pones logged => true a cada item del menu y cuando vas a generar el menu como no envias la variable url el package no tiene nada para construir el menu.
Solution
<ul class="{{ $class }}">
@foreach ($items as $item)
    <li @if ($item['class']) class="{{ $item['class'] }}" @endif id="menu_{{ $item['id'] }}">
    @if ($item['submenu'])
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    @else
        @if (isset($item['url']))
            <a href="{{ $item['url'] }}">
        @endif
    @endif
            {{ $item['title'] }}
            @if ($item['submenu'])
            <b class="caret"></b>
            @endif
        </a>
        @if ($item['submenu'])
        <ul class="dropdown-menu">
            @foreach ($item['submenu'] as $subitem)
            @if (isset($subitem['url']))
            <li><a href="{{ $subitem['url'] }}">{{ $subitem['title'] }}</a></li>
            @endif
            @endforeach
        </ul>
        @endif
    </li>
@endforeach
</ul>

**Comment by sileence** [comment]
¿Puedes enviarme el menú que estabas definiendo por favor?

**Comment by ayalaarevalo** [comment]
'menu' => [
        'home_menu'   => ['url' => '/'],
        'maintenance' => [
            'submenu' => [
                'management' => ['url' => '/managements', 'logged' => true],
                'document_type' => ['url' => '/document_types', 'logged' => true],
            ],
            'callback' => function () { return ! Auth::guest(); }
        ],
        'process' => [
            'submenu' => [
                'document' => ['url' => '/documents']
            ],
        ],
        
        
    ],

**Comment by sileence** [comment]
Si maintenance sólo puede ser visible por usuarios conectados entonces no necesitas colocarle logged true a todos los items del submenu, al no mostrar el padre los hijos tampoco van a aparecer.

De todas formas mejoré el template del menú, por favor descarga los cambios y hazme saber si aún debo arreglar algo más.

¡Gracias por probar el componente!
