### ISSUE TITLE
ID generation for multiselects

### ISSUE THREAD

**Issue by sistemasjg** [StydeNet/html#32]
Hi, when generating multiselects with 

` {!! Field::selectmultiple('categorias[] ......,  ['id'=>'categorias] !!}`

the id of the generated Field is set to categorias[], causing jquery #('categorias')  or #('categorias[]')  not finding the select field

In FieldBuilder.php, function doBuild(....)

the code

`$id =  $this->getHtmlId($name));`

can be changed to:

`$id =  (isset($attributes['id']) ? $attributes['id'] :  $this->getHtmlId($name));`

to gerate the correct id for this control

**Comment by sileence** [comment]
Can you please submit the full code that is causing the error and the full HTML generated? I need to see the full line without the ...... 

Thanks.

**Comment by sistemasjg** [comment]
Template:
` {!! Field::selectmultiple('categorias[]', [], [], 
            ['label'=>'Categorias', 'multiple ', 'id'=>'categorias', 'data-placeholder'=>'Seleccione una o más Categorias', 'class'=>'chosen-select'] )!!}`

Original code produces:

`<select multiple="multiple " id="categorias[]" data-placeholder="Seleccione una o mas categorias" class="form-control chosen-select" name="categorias[]"></select>`

causing `var c = $('#categorias');`  and  `var c = $('#categorias[]');` to fail


Updated Code produces:

`<select multiple="multiple " id="categorias" data-placeholder="Seleccione una o más Categorias" class="form-control chosen-select" name="categorias[]"></select>`

allowing 

`var c = $('#categorias');` to work and add selected and available items via jquery/ajax calls

**Comment by sileence** [comment]
the name of the field (categorias[]) doesn't make sense to me, can't it be just "categorias"?

**Comment by sileence** [comment]
Also if you'd like to have a field like post[categories] or something like that, write it as "post.categories" the component will then generate the appropriate name `post[categories]` and the ID `post_categories`

**Comment by sistemasjg** [comment]
If I name it just categorias, without the brackets, 

the ajax call for saving data throws 

`Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsToMany::formatSyncList() must be of the type array, string given, called in ...`

`$p->categorias()->sync($ct);`

FormData (headers)
`_token:zftpV77sX5ToChV7EYAnZifHGN2CkSkrBCOuGX7Y
categorias:24
categorias:26
categorias:27
id:61`

in the controller, where the form is submited a call to `dd($request::get('categorias'))`;
returns  just "27"

putting the brackets in the name, all works as expected.

Is a ManyToMany Relationship, where the edited model is submited with the selected categories its belongs. I've read in laravel docs and forums that multiselect name must include brackets to allow laravel submit this field as an array.

>> Also if you'd like to have a field like post[categories] or something like that, write it as >>"post.categories" the component will then generate the appropriate name post[categories] and >>the ID post_categories

Let me test it this way. The problem is than I'm filling selected and available categories via jquery/ajax/modal, and because of that, I'm can't use the laravel model/blade syntax in javascript/jquery calls. At least, don't know if is possible

**Comment by sistemasjg** [comment]
You can see the same problem in core laravel form builder, back in 2013

https://github.com/laravel/framework/issues/853
