### ISSUE TITLE
Exception: Illuminate\Contracts\Auth\Access\Gate not found.

### ISSUE THREAD

**Issue by IngwiePhoenix** [StydeNet/html#33]
Is it just me, or does Laravel 5.1 simply not have this?

**Comment by eescalante** [comment]
Same problem here, im using  5.0.33 and Access folder doesn't exist!!!!
What is the requirements in order to install it?

**Comment by sileence** [comment]
@IngwiePhoenix of course it does: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Contracts/Auth/Access/Gate.php 

You need to make sure to have the last version of Laravel 5.1.

@eescalante I recommend you to upgrade to the last version of Laravel 5.1, it takes 30 minutes or less.

**Comment by IngwiePhoenix** [comment]
@sileence Yeah... turns out that Composer nicely decided to not tell me about a version conflict. After I had forced it to try and install 5.1.22, it finally told me that one of my deps was causing this dilemma. Removing said dep bumped Laravel up from 5.1.3 to 5.1.22 - and thus, having me see the changes. Policies and the new Auth stuff works now.

@eescalante Provided with what I had experienced, I advise you to double-check as well. You should see the Laravel version when using `php artisan tinker`. That, at least, is what I had overseen forever...
