### ISSUE TITLE
Cannot use 'String' as class name as it is reserved in PHP7

### ISSUE THREAD

**Issue by DavidClota** [StydeNet/html#36]
FatalErrorException in String.php line 7:
Cannot use 'String' as class name as it is reserved
http://php.net/manual/en/reserved.other-reserved-words.php

**Comment by sileence** [comment]
Wow, thank you for reporting this issue, I will solve it as soon as possible.

**Comment by sileence** [comment]
Fixed, thank you for reporting the issue.

Now you can use the component with Laravel 5.2 as well (branch 1.1) or continue using it with Laravel 5.1 (branch 1.0) and PHP 5 or PHP 7
