### ISSUE TITLE
Menú activa  dos links al mismo tiempo debido al nombre

### ISSUE THREAD

**Issue by cerique** [StydeNet/html#48]
Buenos días. Estoy agregando links  al menú por ejemplo. News y newsletter. Cuando selecciono news queda activo también newsletter debido a que la función hace una búsqueda parcial para agregar la clase active. Cual seria una solución apropiada. Por ahora modifique igualando en la función pero lo hago en el vendor. Pero es algo q no debería hacerse. Quizás  creando una funcion. O también podría estar utilizando mal el componente.  Gracias  por su apoyo.

**Comment by sileence** [comment]
@cerique ahora puedes hacer esto:

```
        Menu::setActiveUrlResolver(function ($values) {
            return // tu lógica aquí
        });
```

y definir la lógica que quieras para determinar si un item debe ser marcado como activo o no.

Estará disponible en las nuevas versiones que estoy marcando este fin de semana para Laravel 5.1, 5.2 y 5.3.
