### ISSUE TITLE
Clase "active" Submenu dentro de un submenu

### ISSUE THREAD

**Issue by daniiprado** [StydeNet/html#60]
Al hacer un submenu dentro de otro, es decir:
`'menu' => [
     'submenu_1' => [
         'submenu_1_1' => [
         ]
     ]
]`

y al entrar al submenu_1_1 no genera la clase "active" para menu, únicamente para "submenu_1" y "submenu_1_1" por favor su ayuda, ¿cómo resuelvo esto?

**Comment by sileence** [comment]
¿Tendrás un ejemplo de esto que me sea fácil reproducir?

**Comment by sileence** [comment]
No te preocupes, ya vi el problema y ya lo solucioné :) Aunque el código es alto rudimentario, funciona bien: https://github.com/StydeNet/html/commit/503817e35db6cd7ed573aa3cd985cdec52f481a3
