### ISSUE TITLE
La clase active generada en varios items

### ISSUE THREAD

**Issue by daniiprado** [StydeNet/html#61]
Al tener urls por ejemplo del tipo

> usuarios/roles
> usuarios/roles/editar

En el menú se genera la clase "active" para ambas opciones.

¿Cómo se puede solucionar esto?
Gracias

**Comment by sileence** [comment]
Hola, ahora podrás usar la opción "exact" similar a vue-router en la versión para Laravel 5.5:

https://github.com/StydeNet/html/commit/fc274447e2a6e2eeff0a080b2b89045078be72b0

También puedes usar `setActiveUrlResolver` para determinar cómo deberían colocarse las URLs activas:

```
        Menu::setActiveUrlResolver(function ($values) {
            return $values['id'] == 'contact-us';
        });
```

En ese ejemplo solo las URLs con el 'id' `contact-us` estarán activas.
