### ISSUE TITLE
Blade components

### ISSUE THREAD

**Issue by m1guelpf** [StydeNet/html#63]
Where is this package usually used on Laravel? On Blade files.
So, what about adding blade directives to make it easier for developers?

**Comment by sileence** [comment]
Any ideas?

**Comment by m1guelpf** [comment]
`@form`, `@html`...

**Comment by sileence** [comment]
The problem is that I'm working in a new version that will allow method chaining, so I don't know how that'd play with those blade directives.

**Comment by nonDeath** [comment]
@sileence in you new version. You change the bootstrap theme to Bs4?

**Comment by sileence** [comment]
@nonDeath it's still Bootstrap3 because B4 is in beta, but I'm working in an update to support both B3 and B4. Maybe you can help me trying it, creating issues and sending Pull requests? I hope to upload something this weekend.

**Comment by m1guelpf** [comment]
@sileence And how about Tailwind?

**Comment by sileence** [comment]
@m1guelpf has that even been released?

**Comment by m1guelpf** [comment]
@sileence Adam said the plan was to release it the 31 Oct.
