### ISSUE TITLE
FieldBuilder in Laravel 5.5

### ISSUE THREAD

**Issue by satoblacksato** [StydeNet/html#65]
verification on attribute required 

Al usar el facades Field :: text en la documentación, indica que el atributo requerido puede ser opcional si se coloca 'required' => false, en la versión 5.5 tengo que hacer la siguiente modificación para el atributo pueda trabajar basado en el valor booleano

~~~
protected function getRequired($attributes)
{
    if (!array_key_exists('required', $attributes)) {
        return true;
    }
    if (isset($attributes['required'])) {
        return $attributes['required'];
    }
    return false;
}



protected function getHtmlAttributes($type, $attributes, $errors, $htmlId, $required)
{
    $attributes['class'] = $this->getClasses($type, $attributes, $errors);
    $attributes['id'] = $htmlId;
    if ($required && !array_key_exists('required', $attributes)) {
        $attributes[] = 'required';
    }
    unset($attributes['template'], $attributes['label']);
    return $attributes;
}
~~~

**Comment by sileence** [comment]
Subí un cambio para simplificar el código, pero no puedo reproducir tu error, es posible que ocurra en otra parte o sea algo de la versión de PHP o del entorno, la verdad no estoy seguro.
