### ISSUE TITLE
Doesn't display errors on "nested" fields

### ISSUE THREAD

**Issue by educolo** [StydeNet/html#67]
I have problems to display errors on "nested" fields.
For example:
`Field::text('address[name]')`
Validation returns with errors but the form doesn't display any.

I understand that in this case I can use address_name, but there are more complex escenarios where it's quite a problem.

**Comment by educolo** [comment]
I made a quick fix on FieldBuilder.php, but I'm not sure if this could give problems with radio buttons validations or some case I'm not aware.

on doBuild() I replaced
`$errors = $this->getControlErrors($id);`
for
`$errors = $this->getControlErrors($name);`

This way works well with dot notation, to work with brackets I need a replace on getControlErrors.

```
protected function getControlErrors($name)
    {
        if ($this->session) {
            
            if ($errors = $this->session->get('errors')) {

                // Replaces to get errors on nested fields
                if (strpos($name, "[")) {
                    $name = str_replace('[', '.', $name);
                    $name = str_replace(']', '', $name);
                }

                return $errors->get($name, []);
            }
        }

        return [];
    }
```

As I said before, I'm not sure if this breaks another validation cases

**Comment by sileence** [comment]
Thanks for reporting this. The current version of this component does not support that feature. But I plan to add it in the next version.

**Comment by IsraelOrtuno** [comment]
I have been testing with this and I think that's the right fix. It does not interfiere with radio inputs as if they contain any brackets in in their name, validation fails the same way as a regular text field.

@sileence can we PR this?

**Comment by sileence** [comment]
@IsraelOrtuno I wasn't thinking on supporting this but if you want to, go ahead, but please submit tests as well.

**Comment by IsraelOrtuno** [comment]
I use this package in all my projects and it looks like a great improvement. Will do.

**Comment by sileence** [comment]
This issue has been now fixed and tag, thanks for the help @educolo  and @IsraelOrtuno
