### ISSUE TITLE
[develop] Improve syntax of select from

### ISSUE THREAD

**Issue by sileence** [StydeNet/html#71]
The new `select` method allows you to chain a call to a new `from` method to fetch data from the database, the params of this method atm are:

* table
* display column
* value column (default to `id`)
* additional query (optional)

```
        $fields->select('parent_id')
            ->from('menu_items', 'label', 'id', function ($query) {
                $query->whereNull('parent_id')
                    ->orderBy('label', 'ASC');
            })
            ->label('Parent');
```

I'm looking for ideas to improve this syntax, make it more flexible etc.

Also this needs integration tests.

**Comment by sileence** [comment]
It just occurred to me that we could pass an object to the from method (maybe rename it to `query`, `using` or even just `options`)

```
        $fields->select('parent_id')
            ->options(From::table('menu_items')->display('label')->value('id')->extra($query) {
                // ...
            })
            ->label('Parent');
```

What do you think?

**Comment by IsraelOrtuno** [comment]
`options` sounds cool to me, or even `fill`. This is a neat feature!

**Comment by sileence** [comment]
@IsraelOrtuno you mean `options` with `From::table`... ?

options is already used to pass static options, so the method could accept an array of static options or a `query` object to fetch dynamic options from the DB

**Comment by IsraelOrtuno** [comment]
I meant with the first example, it looks more obvious to me and most of the times you want fill them with a plain query:

```php
$fields->select('parent_id')
            ->options('menu_items', 'label', 'id')
            ->label('Parent');
```

Probably this is the most common scenario and it just looks neat. It also uses the same syntax as `pluck()`, which is a common method used for this purpose.

 Having to use the Form class is good as well, but less obvious in my opinion:

```php
$fields->select('parent_id')
            ->options(From::table('menu_items')->display('label')->value('id'))
            ->label('Parent');
```

Anyhow, it should be easy to have an implementation for both right? If it's a `Builder` instance, just run `get()` over it.

**Comment by sileence** [comment]
@IsraelOrtuno it's not going to be a builder instance, because I need to specify the display and value columns and I'd be using the extra query to build both the select fields and the `exists` validation rule... (This will generate both HTML and validation)
